import { Inter } from 'next/font/google'
import './style/main.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { MainNav } from '@/sections';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'am Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} container`}>
        <MainNav/>
        {children}
      </body>
    </html>
  )
}
